"""Add pickup_lat and pickup_lng to donations

Revision ID: 6c16ee5ad3a3
Revises: 96fc4a86ec8f
Create Date: 2026-02-20 21:06:58.307093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c16ee5ad3a3'
down_revision = '96fc4a86ec8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pickup_lng', sa.Float(), nullable=True))

    with op.batch_alter_table('pickups', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'requests', ['request_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('pickup_lng')
        batch_op.drop_column('pickup_lat')

    # ### end Alembic commands ###
