"""Add lat and lng to users

Revision ID: 73ffede27b55
Revises: 6c16ee5ad3a3
Create Date: 2026-02-20 21:47:06.075341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ffede27b55'
down_revision = '6c16ee5ad3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###
